[package]
name = "ffxiv-crafter-rust"
version = "0.1.0"
authors = ["amylase <amylase.inquiry@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "experiment"
path = "src/experiment.rs"

[[bin]]
name = "macro_experiment"
path = "src/macro_experiment.rs"

[[bin]]
name = "gen_macro"
path = "src/gen_macro.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63,<=0.2.83"
num = "0.4.0"
rand = "0.8.4"
getrandom = { version = "0.2.3", features = ["js"] }
lazy_static = "1.4.0"
rayon = "1.5.1"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
strum = "0.21"
strum_macros = "0.21"
wasm-timer = "0.2.5"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
